// react/src/App.js
import React, { useState, useEffect } from 'react';

function App({ onMessageSend }) {
  const [inputValue, setInputValue] = useState('');
  const [messageFromHost, setMessageFromHost] = useState('');

  useEffect(() => {
    // Listen for messages from Angular host
    const handleHostMessage = (event) => {
      if (event.detail) {
        setMessageFromHost(event.detail);
        console.log('✅ React received from Host:', event.detail);
      }
    };

    window.addEventListener('hostToReact', handleHostMessage);

    return () => {
      window.removeEventListener('hostToReact', handleHostMessage);
    };
  }, []);

  const handleSend = () => {
    if (onMessageSend && inputValue.trim()) {
      onMessageSend(inputValue);
      setInputValue('');
    }
  };

  return (
    <div style={{ textAlign: 'center', marginTop: '50px' }}>
      <h1>Hello World!</h1>
      <p>Welcome to React</p>
      
      {messageFromHost && (
        <div style={{
          margin: '20px auto',
          padding: '15px',
          background: '#e8f5e9',
          borderRadius: '8px',
          border: '2px solid #4caf50',
          maxWidth: '400px'
        }}>
          <h3 style={{ color: '#2e7d32', margin: '0 0 10px 0' }}>📥 Message from Host:</h3>
          <p style={{ fontSize: '18px', fontWeight: 'bold', margin: 0 }}>{messageFromHost}</p>
        </div>
      )}
      
      <div style={{ marginTop: '30px' }}>
        <input
          type="text"
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          placeholder="Enter a message for Angular"
          style={{
            padding: '10px',
            fontSize: '16px',
            width: '300px',
            marginRight: '10px',
            borderRadius: '4px',
            border: '2px solid #61dafb'
          }}
        />
        <button
          onClick={handleSend}
          style={{
            padding: '10px 20px',
            fontSize: '16px',
            backgroundColor: '#61dafb',
            border: 'none',
            borderRadius: '4px',
            cursor: 'pointer',
            color: '#000'
          }}
        >
          Send to Angular
        </button>
      </div>
    </div>
  );
}

export default App;

// angular/client/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { MessageService } from './message.service';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, FormsModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent implements OnInit {
  title = 'client';
  messageFromReact = '';
  messageFromAngularRemote = '';
  
  // Input values to send to remotes
  messageToReact = '';
  messageToAngularRemote = '';

  constructor(private messageService: MessageService) {}

  ngOnInit() {
    // Listen for messages from React
    this.messageService.message$.subscribe(message => {
      this.messageFromReact = message;
    });

    // Listen for messages from Angular remote (via postMessage from iframe)
    window.addEventListener('message', (event: MessageEvent) => {
      if (event.origin === 'http://localhost:61799' && event.data) {
        this.messageFromAngularRemote = event.data;
        console.log('✅ Message received from Angular remote:', event.data);
      }
    });
  }

  sendToReact() {
    if (this.messageToReact.trim()) {
      // Dispatch custom event that React wrapper can listen to
      window.dispatchEvent(new CustomEvent('hostToReact', { 
        detail: this.messageToReact 
      }));
      console.log('📤 Sent to React:', this.messageToReact);
      this.messageToReact = '';
    }
  }

  sendToAngularRemote() {
    if (this.messageToAngularRemote.trim()) {
      // Send message to iframe via postMessage
      const iframe = document.querySelector('iframe');
      if (iframe && iframe.contentWindow) {
        iframe.contentWindow.postMessage(this.messageToAngularRemote, 'http://localhost:61799');
        console.log('📤 Sent to Angular Remote:', this.messageToAngularRemote);
      }
      this.messageToAngularRemote = '';
    }
  }
}

<h1>Hello World from Angular Host ! 
  @if (messageFromReact) { <span style="color: #00acc1;">React: {{ messageFromReact }}</span> }
  @if (messageFromAngularRemote) { <span style="color: #9c27b0;"> | Angular: {{ messageFromAngularRemote }}</span> }
</h1>

<div style="padding: 20px; background: #e8f5e9; border-radius: 8px; margin: 20px; border: 2px solid #4caf50;">
  <h2 style="color: #2e7d32;">🚀 Send Messages FROM Host TO Remotes</h2>
  
  <div style="margin: 15px 0;">
    <label style="display: block; font-weight: bold; margin-bottom: 5px; color: #00838f;">
      Message to React Remote:
    </label>
    <input 
      [(ngModel)]="messageToReact"
      placeholder="Type message for React..."
      style="padding: 10px; font-size: 16px; width: 300px; margin-right: 10px; border-radius: 4px; border: 2px solid #00acc1;"
    />
    <button 
      (click)="sendToReact()"
      style="padding: 10px 20px; font-size: 16px; background-color: #00acc1; border: none; border-radius: 4px; cursor: pointer; color: white;">
      Send to React
    </button>
  </div>

  <div style="margin: 15px 0;">
    <label style="display: block; font-weight: bold; margin-bottom: 5px; color: #6a1b9a;">
      Message to Angular Remote:
    </label>
    <input 
      [(ngModel)]="messageToAngularRemote"
      placeholder="Type message for Angular..."
      style="padding: 10px; font-size: 16px; width: 300px; margin-right: 10px; border-radius: 4px; border: 2px solid #9c27b0;"
    />
    <button 
      (click)="sendToAngularRemote()"
      style="padding: 10px 20px; font-size: 16px; background-color: #9c27b0; border: none; border-radius: 4px; cursor: pointer; color: white;">
      Send to Angular
    </button>
  </div>
</div>

<router-outlet />
